spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://121.4.113.241:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 541688
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  session:
    timeout: 86400
logging:
  level:
    root: info
    com.cczj: debug
  file:
    path: log/blog.log

comment.avatar: http://cdn.cczjblog.top/cczjBlog-img/avatar_friend_cczj.png
# 处理首次访问网站url后缀带有jsessionid的问题
server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true